// Generated by tools/variants/generate.mjs; edit devices.json instead.
#ifndef ARDUINO_VARIANT_STC8G1K08A_H
#define ARDUINO_VARIANT_STC8G1K08A_H

#define STC_VARIANT_MODEL "STC8G1K08A"
#define STC_VARIANT_FAMILY "STC8G"
#define STC_FLASH_BYTES 8192UL
#define STC_MAXIMUM_CODE_BYTES 8192UL
#define STC_IDATA_BYTES 256U
#define STC_XDATA_BYTES 1024UL
#define STC_EDATA_BYTES 0UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 6U
#define STC_NUM_BONDED_DIGITAL_PINS 6U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 0U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 0
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define STC_VARIANT_PINMUX_PSWX1_BIT0_CLEAR 0
#define PIN_VALID_MASK_P0 0x00U
#define PIN_VALID_MASK_P1 0x00U
#define PIN_VALID_MASK_P2 0x00U
#define PIN_VALID_MASK_P3 0x0FU
#define PIN_VALID_MASK_P4 0x00U
#define PIN_VALID_MASK_P5 0x30U
#define PIN_VALID_MASK_P6 0x00U
#define PIN_VALID_MASK_P7 0x00U
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) (0)
#define STC_VARIANT_PHYSICAL_ALIAS(pin) (NOT_A_PIN)
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 10U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 6U
#define NUM_ANALOG_INPUTS 6
#define A0 P3_0
#define A1 P3_1
#define A2 P3_2
#define A3 P3_3
#define A4 P5_4
#define A5 P5_5
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A5
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P3_0) : \
   ((index) == (1U)) ? (P3_1) : \
   ((index) == (2U)) ? (P3_2) : \
   ((index) == (3U)) ? (P3_3) : \
   ((index) == (4U)) ? (P5_4) : \
   ((index) == (5U)) ? (P5_5) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P3_0)) ? (0U) : \
   ((pin) == (P3_1)) ? (1U) : \
   ((pin) == (P3_2)) ? (2U) : \
   ((pin) == (P3_3)) ? (3U) : \
   ((pin) == (P5_4)) ? (4U) : \
   ((pin) == (P5_5)) ? (5U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P3_0)) ? (0U) : \
   ((pin) == (P3_1)) ? (1U) : \
   ((pin) == (P3_2)) ? (2U) : \
   ((pin) == (P3_3)) ? (3U) : \
   ((pin) == (P5_4)) ? (4U) : \
   ((pin) == (P5_5)) ? (5U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
