// Generated by tools/variants/generate.mjs; edit devices.json instead.
#ifndef ARDUINO_VARIANT_STC8H1K08_H
#define ARDUINO_VARIANT_STC8H1K08_H

#define STC_VARIANT_MODEL "STC8H1K08"
#define STC_VARIANT_FAMILY "STC8H"
#define STC_FLASH_BYTES 8192UL
#define STC_MAXIMUM_CODE_BYTES 8192UL
#define STC_IDATA_BYTES 256U
#define STC_XDATA_BYTES 1024UL
#define STC_EDATA_BYTES 0UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 17U
#define STC_NUM_BONDED_DIGITAL_PINS 17U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 0U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 1
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define STC_VARIANT_PINMUX_PSWX1_BIT0_CLEAR 0
#define PIN_VALID_MASK_P0 0x00U
#define PIN_VALID_MASK_P1 0xFFU
#define PIN_VALID_MASK_P2 0x00U
#define PIN_VALID_MASK_P3 0xFFU
#define PIN_VALID_MASK_P4 0x00U
#define PIN_VALID_MASK_P5 0x10U
#define PIN_VALID_MASK_P6 0x00U
#define PIN_VALID_MASK_P7 0x00U
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) (0)
#define STC_VARIANT_PHYSICAL_ALIAS(pin) (NOT_A_PIN)
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 10U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 9U
#define NUM_ANALOG_INPUTS 9
#define A0 P1_0
#define A1 P1_1
#define A2 P3_0
#define A3 P3_1
#define A4 P3_2
#define A5 P3_3
#define A6 P3_4
#define A7 P3_5
#define A8 P3_6
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A8
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P1_0) : \
   ((index) == (1U)) ? (P1_1) : \
   ((index) == (2U)) ? (P3_0) : \
   ((index) == (3U)) ? (P3_1) : \
   ((index) == (4U)) ? (P3_2) : \
   ((index) == (5U)) ? (P3_3) : \
   ((index) == (6U)) ? (P3_4) : \
   ((index) == (7U)) ? (P3_5) : \
   ((index) == (8U)) ? (P3_6) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P3_0)) ? (2U) : \
   ((pin) == (P3_1)) ? (3U) : \
   ((pin) == (P3_2)) ? (4U) : \
   ((pin) == (P3_3)) ? (5U) : \
   ((pin) == (P3_4)) ? (6U) : \
   ((pin) == (P3_5)) ? (7U) : \
   ((pin) == (P3_6)) ? (8U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P3_0)) ? (8U) : \
   ((pin) == (P3_1)) ? (9U) : \
   ((pin) == (P3_2)) ? (10U) : \
   ((pin) == (P3_3)) ? (11U) : \
   ((pin) == (P3_4)) ? (12U) : \
   ((pin) == (P3_5)) ? (13U) : \
   ((pin) == (P3_6)) ? (14U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
