// Generated by tools/variants/generate.mjs; edit devices.json instead.
#ifndef ARDUINO_VARIANT_STC32CL8K64_H
#define ARDUINO_VARIANT_STC32CL8K64_H

#define STC_VARIANT_MODEL "STC32CL8K64"
#define STC_VARIANT_FAMILY "STC32CL"
#define STC_FLASH_BYTES 65536UL
#define STC_MAXIMUM_CODE_BYTES 65536UL
#define STC_IDATA_BYTES 0U
#define STC_XDATA_BYTES 6144UL
#define STC_EDATA_BYTES 2048UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 19U
#define STC_NUM_BONDED_DIGITAL_PINS 17U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 2U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 1
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define STC_VARIANT_PINMUX_PSWX1_BIT0_CLEAR 0
#define PIN_VALID_MASK_P0 0x0FU
#define PIN_VALID_MASK_P1 0xFCU
#define PIN_VALID_MASK_P2 0x00U
#define PIN_VALID_MASK_P3 0xFFU
#define PIN_VALID_MASK_P4 0x00U
#define PIN_VALID_MASK_P5 0x10U
#define PIN_VALID_MASK_P6 0x00U
#define PIN_VALID_MASK_P7 0x00U
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) \
  (((((left) == (P1_4)) && ((right) == (P0_2))) || (((left) == (P0_2)) && ((right) == (P1_4)))) || \
   ((((left) == (P1_5)) && ((right) == (P0_3))) || (((left) == (P0_3)) && ((right) == (P1_5)))))
#define STC_VARIANT_PHYSICAL_ALIAS(pin) \
  (((pin) == (P1_4)) ? (P0_2) : \
   ((pin) == (P0_2)) ? (P1_4) : \
   ((pin) == (P1_5)) ? (P0_3) : \
   ((pin) == (P0_3)) ? (P1_5) : \
   (NOT_A_PIN))
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 12U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 10U
#define NUM_ANALOG_INPUTS 10
#define A0 P5_4
#define A1 P1_3
#define A2 P1_4
#define A3 P1_5
#define A4 P1_6
#define A5 P1_7
#define A6 P0_0
#define A7 P0_1
#define A8 P0_2
#define A9 P0_3
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A9
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P5_4) : \
   ((index) == (1U)) ? (P1_3) : \
   ((index) == (2U)) ? (P1_4) : \
   ((index) == (3U)) ? (P1_5) : \
   ((index) == (4U)) ? (P1_6) : \
   ((index) == (5U)) ? (P1_7) : \
   ((index) == (6U)) ? (P0_0) : \
   ((index) == (7U)) ? (P0_1) : \
   ((index) == (8U)) ? (P0_2) : \
   ((index) == (9U)) ? (P0_3) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P5_4)) ? (0U) : \
   ((pin) == (P1_3)) ? (1U) : \
   ((pin) == (P1_4)) ? (2U) : \
   ((pin) == (P1_5)) ? (3U) : \
   ((pin) == (P1_6)) ? (4U) : \
   ((pin) == (P1_7)) ? (5U) : \
   ((pin) == (P0_0)) ? (6U) : \
   ((pin) == (P0_1)) ? (7U) : \
   ((pin) == (P0_2)) ? (8U) : \
   ((pin) == (P0_3)) ? (9U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P5_4)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   ((pin) == (P0_3)) ? (11U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
