#!/usr/bin/env python3
"""Generate the fixed-instruction STC32G144K246 NeoPixel transmitters.

The output is compiled by SDCC, never translated through LLVM-CBE. Source-mode
instruction clocks come from the manufacturer's instruction-set appendix.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'libraries/Adafruit_NeoPixel/src/neopixel_stc.c'


def nops(count):
    assert count >= 0
    return ['        nop'] * count


def transmitter(port, bit, scale):
    name = f'np_p{port}{bit}'
    address = (0x80, 0x90, 0xa0, 0xb0, 0xc0, 0xc8, 0xe8, 0xf8)[port] + bit
    pad = f'0x{address:02x}'
    loop = f'{10000 + 2 * (port * 8 + bit)}$'
    done = f'{10001 + 2 * (port * 8 + bit)}$'
    # 12 MHz: 0 high = 4 clocks, 1 high = 8 clocks, period = 15 clocks.
    # 48 MHz: pad every bit to 60 clocks, high times scale by four.
    h0, h1, period = 4 * scale, 8 * scale, 15 * scale
    lines = [f'static void {name}(void) __naked', '{', '    __asm',
             '        push psw', '        push 0xd1', '        push acc',
             '        push dr0', '        push wr4', '        push r8',
             '        mov r0,#0', '        mov r1,_np_data',
             '        mov r2,(_np_data + 1)', '        mov r3,(_np_data + 2)',
             '        mov r4,_np_count', '        mov r5,(_np_count + 1)',
             '        mov r11,@dr0', '        inc dr0,#1', loop + ':']
    for index in range(8):
        lines += ['        rlc a', f'        setb {pad}']
        if index == 7:
            # The allocation has one extra sentinel byte. Prefetch never reads
            # outside that allocation, including at a 64 KiB address crossing.
            lines += ['        mov r8,@dr0'] + nops(h0 - 2)
        else:
            lines += nops(h0 - 1)
        lines += [f'        mov {pad},c']
        if index == 7:
            lines += ['        inc dr0,#1', '        dec wr4,#1'] + nops(h1 - h0 - 3)
        else:
            lines += nops(h1 - h0 - 1)
        lines += [f'        clr {pad}']
        if index < 7:
            lines += nops(period - h1 - 2)
        else:
            # DEC sets Z. The intervening NOP/CLR instructions preserve it.
            lines += [f'        je {done}', '        mov r11,r8']
            lines += nops(period - h1 - 7)
            lines += [f'        ejmp {loop}']
    lines += [done + ':', '        pop r8', '        pop wr4', '        pop dr0',
              '        pop acc', '        pop 0xd1', '        pop psw', '        eret',
              '    __endasm;', '}', '']
    return '\n'.join(lines)


def generate():
    prefix = '''/* Generated by scripts/generate-neopixel-stc.py. Do not edit.
 * SPDX-License-Identifier: MIT
 * Experimental: instruction timing must also be verified on real hardware.
 */
#include "neopixel_stc.h"
#include "Arduino.h"
#include "stc_sfr.h"

static const uint8_t * __data np_data;
static __data uint16_t np_count;

'''
    parts = [prefix]
    for clock, scale in ((12000000, 1), (48000000, 4)):
        parts += [f'#if F_CPU == {clock}UL\n']
        for port in range(8):
            for bit in range(8):
                parts += [transmitter(port, bit, scale)]
        parts += ['#endif\n']
    parts += ['''uint8_t stc_neopixel_supported(int16_t pin, uint8_t is800)
{
    return is800 && pin >= 0 && pin < 0x80 && digitalPinIsValid((uint8_t)pin);
}

uint8_t stc_neopixel_show(const uint8_t *pixels, uint16_t count, int16_t pin, uint8_t is800)
{
    uint8_t saved_ea;
    if (!pixels || !count || !stc_neopixel_supported(pin, is800)) return 0;
    saved_ea = IE & STC_IE_EA;
    IE &= (uint8_t)~STC_IE_EA;
    np_data = pixels;
    np_count = count;
    switch (pin) {
''']
    for port in range(8):
        for bit in range(8):
            parts += [f'    case 0x{port*16+bit:02x}: np_p{port}{bit}(); break;\n']
    parts += ['''    }
    if (saved_ea) IE |= STC_IE_EA;
    return 1;
}
''']
    return '\n'.join(parts)


if __name__ == '__main__':
    OUTPUT.write_text(generate(), encoding='utf-8', newline='\n')
