// Generated by tools/variants/generate.mjs; edit devices.json instead.
#ifndef ARDUINO_VARIANT_AI8051U_34K64_H
#define ARDUINO_VARIANT_AI8051U_34K64_H

#define STC_VARIANT_MODEL "AI8051U-34K64"
#define STC_VARIANT_FAMILY "AI8051U"
#define STC_FLASH_BYTES 65536UL
#define STC_MAXIMUM_CODE_BYTES 65536UL
#define STC_IDATA_BYTES 256U
#define STC_XDATA_BYTES 32768UL
#define STC_EDATA_BYTES 2048UL
#define STC_NUM_LOGICAL_DIGITAL_PINS 46U
#define STC_NUM_BONDED_DIGITAL_PINS 45U
#define STC_VARIANT_PIN_ALIAS_GROUP_COUNT 1U
#define STC_PINOUT_IS_PACKAGE_DEPENDENT 1
#define STC_VARIANT_HAS_UART1 1
#define STC_VARIANT_SERIAL_BUFFERED_RX 1
#define STC_VARIANT_PINMUX_PSWX1_BIT0_CLEAR 0
#define PIN_VALID_MASK_P0 0xFFU
#define PIN_VALID_MASK_P1 0xFFU
#define PIN_VALID_MASK_P2 0xFFU
#define PIN_VALID_MASK_P3 0xFFU
#define PIN_VALID_MASK_P4 0xFFU
#define PIN_VALID_MASK_P5 0xCFU
#define PIN_VALID_MASK_P6 0x00U
#define PIN_VALID_MASK_P7 0x00U
#define STC_VARIANT_PINS_SHARE_PHYSICAL_PAD(left, right) \
  (((((left) == (P4_4)) && ((right) == (P4_5))) || (((left) == (P4_5)) && ((right) == (P4_4)))))
#define STC_VARIANT_PHYSICAL_ALIAS(pin) \
  (((pin) == (P4_4)) ? (P4_5) : \
   ((pin) == (P4_5)) ? (P4_4) : \
   (NOT_A_PIN))
#define STC_VARIANT_HAS_ADC 1
#define STC_VARIANT_ADC_LAYOUT 4U
#define STC_VARIANT_ADC_NATIVE_BITS 12U
#define STC_VARIANT_ADC_BITS STC_VARIANT_ADC_NATIVE_BITS
#define STC_VARIANT_ADC_CHANNEL_COUNT 15U
#define NUM_ANALOG_INPUTS 15
#define A0 P1_0
#define A1 P1_1
#define A2 P1_2
#define A3 P1_3
#define A4 P1_4
#define A5 P1_5
#define A6 P1_6
#define A7 P1_7
#define A8 P0_0
#define A9 P0_1
#define A10 P0_2
#define A11 P0_3
#define A12 P0_4
#define A13 P0_5
#define A14 P0_6
#define STC_VARIANT_FIRST_ANALOG_PIN A0
#define STC_VARIANT_LAST_ANALOG_PIN A14
#define analogInputToDigitalPin(index) \
  (((index) == (0U)) ? (P1_0) : \
   ((index) == (1U)) ? (P1_1) : \
   ((index) == (2U)) ? (P1_2) : \
   ((index) == (3U)) ? (P1_3) : \
   ((index) == (4U)) ? (P1_4) : \
   ((index) == (5U)) ? (P1_5) : \
   ((index) == (6U)) ? (P1_6) : \
   ((index) == (7U)) ? (P1_7) : \
   ((index) == (8U)) ? (P0_0) : \
   ((index) == (9U)) ? (P0_1) : \
   ((index) == (10U)) ? (P0_2) : \
   ((index) == (11U)) ? (P0_3) : \
   ((index) == (12U)) ? (P0_4) : \
   ((index) == (13U)) ? (P0_5) : \
   ((index) == (14U)) ? (P0_6) : \
   (NOT_A_PIN))
#define digitalPinToAnalogInput(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P1_2)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   ((pin) == (P0_3)) ? (11U) : \
   ((pin) == (P0_4)) ? (12U) : \
   ((pin) == (P0_5)) ? (13U) : \
   ((pin) == (P0_6)) ? (14U) : \
   (NOT_AN_ANALOG_INPUT))
#define STC_VARIANT_ADC_PIN_TO_CHANNEL(pin) \
  (((pin) == (P1_0)) ? (0U) : \
   ((pin) == (P1_1)) ? (1U) : \
   ((pin) == (P1_2)) ? (2U) : \
   ((pin) == (P1_3)) ? (3U) : \
   ((pin) == (P1_4)) ? (4U) : \
   ((pin) == (P1_5)) ? (5U) : \
   ((pin) == (P1_6)) ? (6U) : \
   ((pin) == (P1_7)) ? (7U) : \
   ((pin) == (P0_0)) ? (8U) : \
   ((pin) == (P0_1)) ? (9U) : \
   ((pin) == (P0_2)) ? (10U) : \
   ((pin) == (P0_3)) ? (11U) : \
   ((pin) == (P0_4)) ? (12U) : \
   ((pin) == (P0_5)) ? (13U) : \
   ((pin) == (P0_6)) ? (14U) : \
   (NOT_AN_ADC_CHANNEL))

#include "../_common/pins_arduino_common.h"

#endif
